#!/usr/bin/env python3
"""
Pilatus PC-12 Fleet Dashboard Build Script
Generated by Veryon Dashboard Generator
Organization: SINGLE ENGINE TURBOPROP
"""

import json
import csv
import re
from pathlib import Path
from datetime import datetime, date
import pandas as pd

# ---- Paths ----------------------------------------------------------------
BASE_DIR     = Path(__file__).parent.parent
DATA_DIR     = BASE_DIR / "data"
DAILY_CSV    = DATA_DIR / "PC12-Daily-Due-List.csv"
WEEKLY_CSV   = DATA_DIR / "PC12-Long-Range.csv"
HISTORY_JSON = DATA_DIR / "pilatus_pc_12_flight_hours_history.json"
OUTPUT_JSON  = BASE_DIR / "dist" / "data" / "dashboard.json"

# ---- Inspection ATA match strings ----------------------------------------
# Maps ATA prefix -> display name
INSPECTION_MAP = {
    "05 404A AAIP": "600 HOUR OR 12 MONTHS INSPECTION",
    "05 405A AAIP": "1200 HOUR OR 12 MONTHS INSPECTION",
    "05 402A AAIP": "300 HOUR OR 12 MONTHS INSPECTION",
    "05 406A AAIP": "2400 HOUR OR 24 MONTHS INSPECTION",
    "71 0021": "ENGINE - 1750 - 2000 HOUR HOT SECTION INSPECTION"
}

ATA_PREFIXES = ["05 404A AAIP", "05 405A AAIP", "05 402A AAIP", "05 406A AAIP", "71 0021"]

# ---- Component window (hours) --------------------------------------------
COMPONENT_WINDOW = 200

# ---- Helpers --------------------------------------------------------------
def _norm(x):
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return None
    return str(x).strip()

def _read_csv(path):
    for enc in ("utf-8-sig", "cp1252", "utf-8"):
        try:
            return pd.read_csv(path, encoding=enc, dtype=str, low_memory=False)
        except UnicodeDecodeError:
            continue
    return pd.read_csv(path, encoding="latin-1", dtype=str, low_memory=False)

def load_history():
    if HISTORY_JSON.exists():
        with open(HISTORY_JSON, encoding="utf-8") as f:
            return json.load(f)
    return {}

def save_history(history):
    HISTORY_JSON.parent.mkdir(parents=True, exist_ok=True)
    with open(HISTORY_JSON, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2)

def collect_snapshots(df):
    df = df.copy()
    df.columns = [c.lstrip("\ufeff").strip() for c in df.columns]
    snapshots = []
    for _, row in df.iterrows():
        tail  = _norm(row.get("Registration Number",""))
        hrs   = pd.to_numeric(row.get("Airframe Hours", row.get("Total Time","")), errors="coerce")
        rdate = _norm(row.get("Report Date", row.get("Export Date","")))
        if tail and not pd.isna(hrs) and rdate:
            try:
                dt = datetime.strptime(rdate, "%m/%d/%Y").date().isoformat()
            except ValueError:
                try:
                    dt = datetime.strptime(rdate, "%Y-%m-%d").date().isoformat()
                except ValueError:
                    continue
            snapshots.append((tail, dt, float(hrs)))
    return snapshots

def update_history(history, snapshots):
    for tail, dt, hrs in snapshots:
        if tail not in history:
            history[tail] = {}
        if dt not in history[tail]:
            history[tail][dt] = hrs
    return history

def calculate_utilization(history):
    util = {}
    today = date.today()
    for tail, entries in history.items():
        if len(entries) < 2:
            util[tail] = {"avg_daily": None, "projection_weekly": None,
                          "projection_monthly": None, "daily_data": list(
                              {"date": d, "hours": h} for d, h in sorted(entries.items())
                          )}
            continue
        sorted_entries = sorted(entries.items())
        daily_data = [{"date": d, "hours": h} for d, h in sorted_entries]

        # Try 30-day span
        cutoff_30 = (today - __import__("datetime").timedelta(days=30)).isoformat()
        recent_30 = [(d, h) for d, h in sorted_entries if d >= cutoff_30]

        if len(recent_30) >= 2:
            span_days = (datetime.fromisoformat(recent_30[-1][0]) -
                         datetime.fromisoformat(recent_30[0][0])).days
            if span_days > 0:
                avg = (recent_30[-1][1] - recent_30[0][1]) / span_days
            else:
                avg = 0.0
        else:
            # Fall back to any available span
            span_days = (datetime.fromisoformat(sorted_entries[-1][0]) -
                         datetime.fromisoformat(sorted_entries[0][0])).days
            avg = (sorted_entries[-1][1] - sorted_entries[0][1]) / span_days if span_days > 0 else 0.0

        avg = max(0.0, avg)
        util[tail] = {
            "avg_daily":          round(avg, 3),
            "projection_weekly":  round(avg * 7, 2),
            "projection_monthly": round(avg * 30, 2),
            "daily_data":         daily_data,
        }
    return util

def match_inspection(ata_code):
    if not ata_code:
        return None
    ata_upper = str(ata_code).upper()
    for prefix in ATA_PREFIXES:
        if prefix.upper() in ata_upper:
            return INSPECTION_MAP.get(prefix, prefix)
    return None

def urgency_key(item):
    d = item.get("remaining_days")
    h = item.get("remaining_hours")
    if d is not None:
        return (0, float(d))
    if h is not None:
        return (1, float(h))
    return (2, 0)

# ---- Main build -----------------------------------------------------------
def build():
    # Load and update history
    history = load_history()
    daily_df = _read_csv(DAILY_CSV)
    daily_df.columns = [c.lstrip("\ufeff").strip() for c in daily_df.columns]

    snaps = collect_snapshots(daily_df)
    history = update_history(history, snaps)

    if WEEKLY_CSV and WEEKLY_CSV.exists():
        weekly_df = _read_csv(WEEKLY_CSV)
        weekly_df.columns = [c.lstrip("\ufeff").strip() for c in weekly_df.columns]
        snaps2 = collect_snapshots(weekly_df)
        history = update_history(history, snaps2)

    save_history(history)
    utilization = calculate_utilization(history)

    # Filter inspection rows only
    insp_df = daily_df[daily_df["Item Type"].astype(str).str.upper() == "INSPECTION"].copy()

    # Parse numeric fields
    insp_df["Remaining Hours"] = pd.to_numeric(insp_df.get("Remaining Hours",""), errors="coerce")
    insp_df["Remaining Days"]  = pd.to_numeric(insp_df.get("Remaining Days",""),  errors="coerce")

    # Get report date from most common date in export
    try:
        report_date = insp_df["Report Date"].dropna().mode()[0]
        report_date = datetime.strptime(report_date, "%m/%d/%Y").date().isoformat()
    except Exception:
        report_date = date.today().isoformat()

    # Build aircraft dict
    aircraft_dict = {}
    for _, row in insp_df.iterrows():
        tail  = _norm(row.get("Registration Number","")) or "UNKNOWN"
        ata   = _norm(row.get("ATA and Code",""))
        insp  = match_inspection(ata)
        if not insp:
            continue

        if tail not in aircraft_dict:
            tt = pd.to_numeric(row.get("Airframe Hours", row.get("Total Time","")), errors="coerce")
            aircraft_dict[tail] = {
                "airframe_hours":       float(tt) if not pd.isna(tt) else None,
                "airframe_report_date": report_date,
                "items": []
            }

        rd = row["Remaining Days"]
        rh = row["Remaining Hours"]
        nd = _norm(row.get("Next Due Date",""))
        status = _norm(row.get("Next Due Status", row.get("Status","")))

        aircraft_dict[tail]["items"].append({
            "inspection":      insp,
            "ata":             ata,
            "description":     _norm(row.get("Description","")),
            "due_date":        nd,
            "remaining_days":  float(rd) if not pd.isna(rd) else None,
            "remaining_hours": float(rh) if not pd.isna(rh) else None,
            "next_due_status": status,
            "status":          _classify(rd, rh, status),
        })

    for data in aircraft_dict.values():
        data["items"].sort(key=urgency_key)

    aircraft_list = []
    for tail in sorted(aircraft_dict.keys()):
        data = aircraft_dict[tail]
        util = utilization.get(tail, {})
        aircraft_list.append({
            "tail":               tail,
            "airframe_hours":     data["airframe_hours"],
            "airframe_report_date": data["airframe_report_date"],
            "avg_daily":          util.get("avg_daily"),
            "projection_weekly":  util.get("projection_weekly"),
            "projection_monthly": util.get("projection_monthly"),
            "daily_data":         util.get("daily_data", []),
            "items":              data["items"],
        })

    # Components
    components = []
    parts = daily_df[daily_df["Item Type"].astype(str).str.upper() == "PART"].copy()
    parts["Remaining Hours"] = pd.to_numeric(parts["Remaining Hours"], errors="coerce")
    for _, row in parts.iterrows():
        rh = row["Remaining Hours"]
        if pd.isna(rh) or rh > COMPONENT_WINDOW:
            continue
        components.append({
            "tail":            _norm(row.get("Registration Number","")),
            "ata":             _norm(row.get("ATA and Code","")),
            "description":     _norm(row.get("Description","")),
            "item_type":       "PART",
            "remaining_hours": float(rh),
        })

    insp_oh = daily_df[
        (daily_df["Item Type"].astype(str).str.upper() == "INSPECTION") &
        (daily_df["Requirement Type"].astype(str).str.upper() == "OVERHAUL")
    ].copy()
    insp_oh["Remaining Hours"] = pd.to_numeric(insp_oh["Remaining Hours"], errors="coerce")
    for _, row in insp_oh.iterrows():
        rh = row["Remaining Hours"]
        if pd.isna(rh) or rh > COMPONENT_WINDOW:
            continue
        components.append({
            "tail":            _norm(row.get("Registration Number","")),
            "ata":             _norm(row.get("ATA and Code","")),
            "description":     _norm(row.get("Description","")),
            "item_type":       "OVERHAUL",
            "remaining_hours": float(rh),
        })
    components.sort(key=lambda c: c["remaining_hours"])

    out = {
        "meta": {
            "report_date":    report_date,
            "generated_utc":  datetime.utcnow().isoformat(timespec="seconds") + "Z",
            "fleet_name":     "Pilatus PC-12",
            "source":         str(DAILY_CSV),
            "aircraft_count": len(aircraft_list),
        },
        "aircraft":   aircraft_list,
        "components": components,
    }

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)

    print(f"Read:    {DAILY_CSV} ({len(insp_df)} inspection rows)")
    print(f"History: {HISTORY_JSON} ({sum(len(v) for v in history.values())} total snapshots)")
    print(f"Built:   {OUTPUT_JSON} ({len(aircraft_list)} aircraft)")
    print(f"Comps:   {len(components)} within {COMPONENT_WINDOW}h")

def _classify(rd, rh, status):
    if rd is not None and not (isinstance(rd, float) and pd.isna(rd)):
        d = float(rd)
        if d < 0:   return "OVERDUE"
        if d <= 7:  return "CRITICAL"
        if d <= 30: return "COMING DUE"
        return "OK"
    if rh is not None and not (isinstance(rh, float) and pd.isna(rh)):
        h = float(rh)
        if h < 0:    return "OVERDUE"
        if h <= 25:  return "CRITICAL"
        if h <= 100: return "COMING DUE"
        return "OK"
    s = str(status).upper() if status else ""
    if "PAST DUE" in s or "OVERDUE" in s: return "OVERDUE"
    if "CRITICAL" in s:  return "CRITICAL"
    if "COMING" in s:    return "COMING DUE"
    return "OK"

if __name__ == "__main__":
    build()
